apiVersion: v1
kind: Service
metadata:
  name: cis-test-generator
  namespace: teg-cis-dev
spec:
  selector:
    app: teg-cis
    component: cis-test-generator
  ports:
  - protocol: TCP
    port: 8050
    targetPort: 8050
  type: ClusterIP