apiVersion: v1
kind: Service
metadata:
  name: cis-message-proxy
  namespace: teg-cis-dev
spec:
  selector:
    app: teg-cis
    component: cis-message-proxy
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: mobile  