apiVersion: v1
kind: Service
metadata:
  name: cis-device
  namespace: teg-cis-dev
spec:
  selector:
    app: teg-cis
    component: cis-device
  ports:
  - protocol: TCP
    port: 8020
    targetPort: 8020
  type: ClusterIP