apiVersion: v1
kind: Service
metadata:
  name: cis-notification
  namespace: teg-cis-dev
spec:
  selector:
    app: teg-cis
    component: cis-notification
  ports:
  - protocol: TCP
    port: 8030
    targetPort: 8030
  type: ClusterIP