apiVersion: v1
kind: Service
metadata:
  name: cis-subscription
  namespace: teg-cis-dev
spec:
  selector:
    app: teg-cis
    component: cis-subscription
  ports:
  - protocol: TCP
    port: 8040
    targetPort: 8040
  type: ClusterIP