apiVersion: v1
kind: Service
metadata:
  name: service-registrator
  namespace: teg-cis-dev
spec:
  selector:
    app: teg-cis
    component: service-registrator
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: ClusterIP