apiVersion: apps/v1
kind: Deployment
metadata:
  name: cis-notification
  labels:
    app: teg-cis
    component: cis-notification
  namespace: teg-cis-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teg-cis
      component: cis-notification
  template:
    metadata:
      labels:
        app: teg-cis
        component: cis-notification                             
    spec:
      containers:
      - name: cis-notification 
        image: localhost:32000/teg/cis-notification:latest-dev
        ports:
        - containerPort: 8030        
        env:
        - name: SERVICE_NAME
          value: cis-notification
        envFrom:
          - configMapRef:
              name: $(POD_NAMESPACE)/db-env-config
          - configMapRef:
              name: $(POD_NAMESPACE)/api-env-config
          - configMapRef:
              name: $(POD_NAMESPACE)/teg-env-config
