apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registrator
  labels:
    app: teg-cis
    component: service-registrator
  namespace: teg-cis-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teg-cis
      component: service-registrator
  template:
    metadata:
      labels:
        app: teg-cis
        component: service-registrator                           
    spec:
      containers:
      - name: service-registrator 
        image: localhost:32000/teg/service-registrator:latest-dev
        ports:
        - containerPort: 4000        
        env:
        - name: SERVICE_NAME
          value: service-registrator
        #envFrom:
        #  - configMapRef:
        #      name: $(POD_NAMESPACE)/db-env-config
        #  - configMapRef:
        #      name: $(POD_NAMESPACE)/api-env-config
        #  - configMapRef:
        #      name: $(POD_NAMESPACE)/teg-env-config